name: public_chat
description: "A Public Chat app to chat with Gemini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_generative_ai: ^0.4.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
