name: public_chat
description: "A Public Chat app to chat with Gemini."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  # Core flutter
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4+2

  # Update UI with Firestore pagination
  firebase_ui_firestore: ^1.6.3

  # Bloc
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # SVG Display
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0

  # Gemini for GenAI chat
  google_generative_ai: ^0.4.3
  image_network: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
